name: build mac

on:
  workflow_dispatch:
  push:
    tags:
      - 'release*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-14 ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven
        run: |
          mvn verify -DskipTests -DskipSign
          mkdir ./res
          mv osx/target/Cyberduck.app ./res
      - uses: actions/upload-artifact@v4
        with:
          name: Cyberduck.app
          path: ./res

