name: build mac

on:
  workflow_dispatch:
  push:
    tags:
      - 'release*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-15 ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Build with Maven
        run: |
          mvn verify -DskipTests -DskipSign
          mkdir ./res
          mv osx/target/Cyberduck.app ./res
      - uses: actions/upload-artifact@v4
        with:
          name: Cyberduck.app
          path: ./res

